### ISSUE TITLE
SSN False Positive in compiled CSS [Trusted]

### ISSUE THREAD

**Issue by hale** [Arachni/arachni#170]
The manifest `application.css` file compiled by the Rails framework resulted in a SSN issue.  The CSS is an almost untouched Twitter Bootstrap framework, so it's probably something there.
### Source of the issue

http://pastebin.com/V3G7QBr6
### Speculation

The following lines stood out to me as looking a bit like SSN's

``` css
.row-fluid > .span12{width:99.99999998999999%;}
.row-fluid > .span11{width:91.489361693%;}
.row-fluid > .span10{width:82.97872339599999%;}
.row-fluid > .span9{width:74.468085099%;}
```
