### ISSUE TITLE
How to audit xml in a raw body with feed vector plugin?

### ISSUE THREAD

**Issue by aiddroid** [Arachni/arachni#984]
Is there anything wrong?
command:
```shell
/bin/arachni 'http://xxx/xxe.php' '--scope-page-limit' '1' '--report-save-path' 'output.afr' "--plugin" "vector_feed:yaml_file=feed.yaml"
```

feed.yaml file:
```yaml
action: http://xxx/xxe.php
inputs: <creds><user>admin</user><pass>mypass</pass></creds>
method: post
type: xml
```

**Comment by aiddroid** [comment]
my fault, the yaml file shoule be:
```yaml
action: http://xxx/xxe.php
method: post
type: xml
source: <creds><user>admin</user><pass>mypass</pass></creds>
```
